---
defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
      title: "this is site.title"
      description: "this is site.description"
---
lsi: false
safe: true
source: docs
verbose: true
show_dir_listing: true
incremental: false
highlighter: rouge
gist:
  noscript: false
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge
permalink: /:year/:month/:day/:title:output_ext
baseurl: /gh-pages-test
theme: jekyll-theme-tactile
#remote_theme: "mmistakes/minimal-mistakes@4.24.0"
#rlugins:
#  - jekyll-paginate
#  - jekyll-sitemap
#  - jekyll-gist
#  - jekyll-feed
#  - jemoji
#  - jekyll-include-cache
