lsi: false
safe: true
source: docs
verbose: true
show_dir_listing: true
incremental: false
highlighter: rouge
gist:
  noscript: false
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge
theme: minimal

